# Fonte
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

# Estética da Janela
hide_window_decorations no
window_padding_width    10
background_opacity      1
# background_blur: Linux only (no macOS equivalent)
background_blur         1

# Cores (Tema minimalista focado em código)
foreground #cdd6f4
background #1e1e2e
cursor     #f5e0dc

# Performance
repaint_delay   10
input_delay     3
sync_to_monitor yes

# Ativa o layout de splits (essencial para o comportamento do Terminator)
enabled_layouts splits:split_axis=horizontal

# Atalhos idênticos aos do Terminator para dividir a tela
map ctrl+shift+e launch --location=vsplit
map ctrl+shift+o launch --location=hsplit

# Fechar o split atual
map ctrl+shift+w close_window

# Atalhos para navegar entre os splits usando Alt + Setas
map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down

editor micro
