# ==========================================
# Fonte
# ==========================================
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.0

# ==========================================
# Estética da Janela
# ==========================================
# 'no' mostra botões de fechar/minimizar/maximizar; 'titlebar-only' esconde só os botões no macOS.
hide_window_decorations no
window_padding_width    12
background_opacity      0.95
background_blur         10

# ==========================================
# Barra de Abas (Tab Bar)
# ==========================================
tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
active_tab_font_style       bold-italic

# Performance
repaint_delay   10
input_delay     3
sync_to_monitor yes

# Ativa o layout de splits (essencial para o comportamento do Terminator)
enabled_layouts splits:split_axis=horizontal

# Atalhos idênticos aos do Terminator para dividir a tela
map ctrl+shift+e launch --location=vsplit
map ctrl+shift+o launch --location=hsplit

# Fechar o split atual
map ctrl+shift+w close_window

# Atalhos para navegar entre os splits usando Alt + Setas
map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down

editor micro

# BEGIN_KITTY_THEME
# Phanes
include current-theme.conf
# END_KITTY_THEME
